Repository COSC481W-2021Fall/capstone-adam-and-the-mod-squad, pull requests merged in 2021-12, with the labels that each got.

#113 impl: Buy me a coffee acct
  mydjangoproject/muninn/templates/muninn/about.html
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint4

#118 Feature: Edit Tasks and Habits
  mydjangoproject/muninn/static/muninn/scripts.js
  mydjangoproject/muninn/templates/muninn/task_list.html
  mydjangoproject/muninn/views.py
Labels: enhancement, Essential Features, sprint4

#119 impl: Name Randomizer Button
  mydjangoproject/muninn/functions.py
  mydjangoproject/muninn/static/muninn/images/refresh.png
  mydjangoproject/muninn/static/muninn/random_names.txt
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/pet_shop.html
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint4

#114 style: Changed price and level of animals
  djangoprojectdb.sql
Labels: style, sprint4

#116 style: faq page
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/faq.html
  mydjangoproject/muninn/urls.py
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint4

#126 bug: Fixed level and gold
  mydjangoproject/muninn/views.py
Labels: bug, sprint4

#127 impl: add ability to page through past days
  mydjangoproject/muninn/functions.py
  mydjangoproject/muninn/static/muninn/images/left-arrow.png
  mydjangoproject/muninn/static/muninn/images/right-arrow.png
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/task_list.html
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint4

#124 feature: added Stick Cat as an Easter Egg
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint4

#123 chore: Added info on editing task
  mydjangoproject/muninn/templates/muninn/faq.html
Labels: style, sprint4

#122 bug: Made it so you can get onto Stats
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/views.py
Labels: bug, sprint4

#128 fix: views and redirects + features
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/pet_shop.html
  mydjangoproject/muninn/templates/muninn/roost.html
  mydjangoproject/muninn/templates/muninn/statistics.html
  mydjangoproject/muninn/views.py
Labels: bug, style, sprint4
