Repository COSC481W-2021Fall/capstone-adam-and-the-mod-squad, pull requests merged in 2021-11, with the labels that each got.

#64 Fix: Added account alerts to base.html
  mydjangoproject/muninn/static/muninn/scripts.js
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/message.html
  mydjangoproject/muninn/templates/muninn/task_list.html
  mydjangoproject/muninn/views.py
  mydjangoproject/users/templates/users/login.html
  mydjangoproject/users/templates/users/register.html
Labels: bug, sprint2

#65 Andreaka fix style bugs
  .gitignore
  mydjangoproject/muninn/migrations/0001_initial.py
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/about.html
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/friends.html
  mydjangoproject/muninn/templates/muninn/home.html
  mydjangoproject/muninn/templates/muninn/message.html
  mydjangoproject/muninn/templates/muninn/pet_shop.html
  mydjangoproject/muninn/templates/muninn/roost.html
  mydjangoproject/muninn/templates/muninn/statistics.html
  mydjangoproject/muninn/templates/muninn/user_settings.html
Labels: bug, sprint2, style

#76 fix: Account Link bug
  mydjangoproject/users/templates/users/register.html
Labels: bug, Essential Features, sprint3

#77 style: Add daily percent bar
  mydjangoproject/muninn/migrations/0001_initial.py
  mydjangoproject/muninn/migrations/0002_auto_20211029_1629.py
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/task_list.html
Labels: style, sprint3

#78 fix: add task/habit allowing blank tasks/habits
  mydjangoproject/muninn/migrations/0001_initial.py
  mydjangoproject/muninn/views.py
Labels: bug, sprint3

#79 bug: Cleaned up CSS
  mydjangoproject/muninn/static/muninn/styles.css
Labels: bug, sprint3

#82 bug:Sara clean up css bug
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/message.html
Labels: bug, sprint3

#83 Jesse sakib connect back to front
  mydjangoproject/muninn/functions.py
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/task_list.html
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint3

#84 Style: jesse-sara-styling-bugs
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/pet_shop.html
Labels: bug, style, sprint3

#85 impl: Roost page and functionalities
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/pet_shop.html
  mydjangoproject/muninn/templates/muninn/roost.html
  mydjangoproject/muninn/views.py
Labels: Essential Features, sprint3

#88 style: Create meme animals
  mydjangoproject/muninn/static/muninn/images/cowboy_hat_cat.png
  mydjangoproject/muninn/static/muninn/images/doge.png
  mydjangoproject/muninn/static/muninn/images/fire_gator.png
  mydjangoproject/muninn/static/muninn/images/grumpyMeme.png
  mydjangoproject/muninn/static/muninn/images/memeAngryDuck.png
  mydjangoproject/muninn/static/muninn/images/memeCat1.png
  mydjangoproject/muninn/static/muninn/images/memeCat2.png
  mydjangoproject/muninn/static/muninn/images/memeCat3.png
  mydjangoproject/muninn/static/muninn/images/memeDeer.png
  mydjangoproject/muninn/static/muninn/images/memeDog1.png
  mydjangoproject/muninn/static/muninn/images/memeDog2.png
  mydjangoproject/muninn/static/muninn/images/memeDog3.png
  mydjangoproject/muninn/static/muninn/images/memeDog4.png
  mydjangoproject/muninn/static/muninn/images/memeFish.png
  mydjangoproject/muninn/static/muninn/images/memeHamster.png
  mydjangoproject/muninn/static/muninn/images/memeSeal.png
Labels: style, sprint3

#89 fix: percentageToNextLevel func
  mydjangoproject/muninn/functions.py
  mydjangoproject/muninn/views.py
Labels: bug

#91 fix: fix some styles for the pet shop
  mydjangoproject/muninn/static/muninn/styles.css
Labels: bug, style, sprint3

#93 fix: sidebar not showing level and money
  mydjangoproject/muninn/views.py
Labels: bug, style, sprint3

#106 style: Roost now lights up
  mydjangoproject/muninn/templates/muninn/base.html
Labels: style, sprint4

#108 style: Got rid of the picture of Chiara
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/friends.html
  mydjangoproject/muninn/templates/muninn/task_list.html
Labels: style, sprint4

#107 style: Got rid of Settings
  mydjangoproject/muninn/templates/muninn/base.html
Labels: style, sprint4

#110 Sara jesse fix about me buttons
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/about.html
Labels: bug, style, sprint4

#111 fix: Spacing bug and required fields
  mydjangoproject/muninn/static/muninn/images/Muninn_roost_updated
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/pet_shop.html
  mydjangoproject/muninn/templates/muninn/roost.html
  mydjangoproject/muninn/views.py
Labels: bug, style, sprint4

#109 Sara update database
  djangoprojectdb.sql
Labels: enhancement, sprint4
