Repository COSC481W-2021Fall/capstone-adam-and-the-mod-squad, pull requests merged in 2021-10, with the labels that each got.

#18 fix: Migrations not working
  mydjangoproject/mydjangoproject/settings.py
Labels: bug

#21 fix: Folder creation for templates and user
  mydjangoproject/muninn/urls.py
  mydjangoproject/mydjangoproject/settings.py
  mydjangoproject/users/__init__.py
  mydjangoproject/users/admin.py
  mydjangoproject/users/apps.py
  mydjangoproject/users/migrations/__init__.py
  mydjangoproject/users/models.py
  mydjangoproject/users/tests.py
  mydjangoproject/users/views.py
Labels: bug

#22 setup for phpmyadmin
  mydjangoproject/muninn/admin.py
  mydjangoproject/muninn/migrations/0001_initial.py
  mydjangoproject/muninn/migrations/0002_employees_muninnuserv2.py
  mydjangoproject/muninn/models.py
Labels: enhancement, sprint1

#23 cleanup of models.py
  mydjangoproject/muninn/admin.py
  mydjangoproject/muninn/models.py
Labels: enhancement

#26 fix: Github doesn't include empty folders
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/users/templates/users/login.html
Labels: bug

#31 Feature: Home Page and Base Template
  mydjangoproject/muninn/migrations/0003_auto_20211006_1453.py
  mydjangoproject/muninn/static/muninn/datatables-simple-demo.js
  mydjangoproject/muninn/static/muninn/images/logo.png
  mydjangoproject/muninn/static/muninn/scripts.js
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/home.html
  mydjangoproject/muninn/urls.py
  mydjangoproject/muninn/views.py
  mydjangoproject/mydjangoproject/settings.py
  mydjangoproject/mydjangoproject/urls.py
  mydjangoproject/users/templates/users/login.html
  mydjangoproject/users/templates/users/logout.html
  mydjangoproject/users/templates/users/register.html
  mydjangoproject/users/urls.py
  mydjangoproject/users/views.py
Labels: Essential Features, sprint1

#28 feature: User log in/out
  mydjangoproject/muninn/migrations/0003_auto_20211006_1453.py
  mydjangoproject/muninn/static/muninn/datatables-simple-demo.js
  mydjangoproject/muninn/static/muninn/scripts.js
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/home.html
  mydjangoproject/muninn/urls.py
  mydjangoproject/muninn/views.py
  mydjangoproject/mydjangoproject/settings.py
  mydjangoproject/mydjangoproject/urls.py
  mydjangoproject/users/templates/users/login.html
  mydjangoproject/users/templates/users/logout.html
  mydjangoproject/users/templates/users/register.html
  mydjangoproject/users/urls.py
  mydjangoproject/users/views.py
Labels: Essential Features, sprint1

#36 Jesse sakib complete task
  mydjangoproject/muninn/admin.py
  mydjangoproject/muninn/templates/muninn/task_list.html
  mydjangoproject/muninn/views.py
Labels: Essential Features, sprint1

#38 fix: add delete button
  mydjangoproject/muninn/templates/muninn/task_list.html
Labels: bug, sprint1

#52 impl: add blank pages
  mydjangoproject/muninn/templates/muninn/about.html
  mydjangoproject/muninn/templates/muninn/friends.html
  mydjangoproject/muninn/templates/muninn/pet_shop.html
  mydjangoproject/muninn/templates/muninn/roost.html
  mydjangoproject/muninn/templates/muninn/statistics.html
  mydjangoproject/muninn/templates/muninn/user_settings.html
  mydjangoproject/muninn/urls.py
  mydjangoproject/muninn/views.py
Labels: enhancement, sprint2

#58 style: Add 10 animals
  mydjangoproject/muninn/static/muninn/images/Black Pig.png
  mydjangoproject/muninn/static/muninn/images/Blue Crab.png
  mydjangoproject/muninn/static/muninn/images/Blue Dragon.png
  mydjangoproject/muninn/static/muninn/images/Blue Koala.png
  mydjangoproject/muninn/static/muninn/images/Brown Pig.png
  mydjangoproject/muninn/static/muninn/images/Brown Rat.png
  mydjangoproject/muninn/static/muninn/images/Grey Koala.png
  mydjangoproject/muninn/static/muninn/images/Grey Rat.png
  mydjangoproject/muninn/static/muninn/images/Pink Pig.png
  mydjangoproject/muninn/static/muninn/images/Purple Dragon.png
  mydjangoproject/muninn/static/muninn/images/Purple Pufferfish.png
  mydjangoproject/muninn/static/muninn/images/Rainbow Crab.png
  mydjangoproject/muninn/static/muninn/images/Rainbow Koala.png
  mydjangoproject/muninn/static/muninn/images/Red Crab.png
  mydjangoproject/muninn/static/muninn/images/Red Dragon.png
  mydjangoproject/muninn/static/muninn/images/Red Pufferfish.png
  mydjangoproject/muninn/static/muninn/images/White Rat.png
  mydjangoproject/muninn/static/muninn/images/Yellow Pufferfish.png
  mydjangoproject/muninn/static/muninn/images/blue slime.png
  mydjangoproject/muninn/static/muninn/images/hippocampus_blue.png
  mydjangoproject/muninn/static/muninn/images/hippocampus_brown.png
  mydjangoproject/muninn/static/muninn/images/hippocampus_pink.png
  mydjangoproject/muninn/static/muninn/images/narwhal_normal.png
  mydjangoproject/muninn/static/muninn/images/narwhal_starry.png
  mydjangoproject/muninn/static/muninn/images/narwhal_sunset.png
  mydjangoproject/muninn/static/muninn/images/pink slime.png
  mydjangoproject/muninn/static/muninn/images/purple slime.png
  mydjangoproject/muninn/static/muninn/images/stickFigureCat.png
  mydjangoproject/muninn/static/muninn/images/wolf_dark.png
  mydjangoproject/muninn/static/muninn/images/wolf_natural.png
  mydjangoproject/muninn/static/muninn/images/wolf_white.png
Labels: Essential Features, sprint2

#59 Andreaka daily reset
  mydjangoproject/muninn/functions.py
  mydjangoproject/muninn/migrations/0002_auto_20211029_1629.py
  mydjangoproject/muninn/models.py
  mydjangoproject/muninn/views.py
Labels: Essential Features, sprint2

#60 Feature: Progress Bar and Stats
  mydjangoproject/muninn/static/muninn/styles.css
  mydjangoproject/muninn/templates/muninn/base.html
  mydjangoproject/muninn/templates/muninn/task_list.html
Labels: Essential Features, sprint2
